def color_pool_for_letter(letter: str, year: int | None = None):
    letter = letter.upper()
    pools = {
        'A': ['Almond','Amethyst','Apple','Apricot','Aqua','Aquamarine','Arctic','Asparagus','Atomic','Auburn','Azalea','Azure','Amber','Ash','Alizarin','Amaranth','Antique','Amulet','Anise','Atlantis','Alpine','Anchor','Aurora','Avocado','Amour','Amphibian','Aviator','Apollo','Ardor','Atlas'],
        'B': ['Banana','Beaver','Beige','Berry','Bittersweet','Black','Blizzard','Bluebell','Blush','Bordeaux','Brass','Brick','Bronze','Brown','Bubblegum','Buff','Burgundy','Burlap','Butter','Buttermilk','Byzantium','Bayou','Beryl','Biscuit','Bison','Basil','Bamboo','Ballet','Bonsai','Beryl'],
        'C': ['Camel','Canary','Caramel','Carnation','Carrot','Celeste','Cerise','Cerulean','Champagne','Charcoal','Chartreuse','Cherry','Chestnut','Chocolate','Cinnamon','Citrus','Claret','Cobalt','Coconut','Coffee','Copper','Coral','Cornflower','Cotton','Cream','Crimson','Cyan','Curry','Cypress','Cyclamen'],
        'D': ['Daffodil','Dahlia','Daisy','Dandelion','Denim','Desert','Dijon','Dove','Dragonfruit','Driftwood','Dusty','Dusk','Dawn','Dynamo','Dynamo','Dingo','Dingo','Delft','Dingo','Diva','Dingo','Domino','Doodle','Dingo','Draco','Dream','Delta','Dingo','Dome','Dynamo'],
        'E': ['Ebony','Ecru','Eggplant','Emerald','Erin','Evergreen','Elderberry','Earth','Eagle','Eclipse','Egret','Element','Elm','Ember','Envy','Epic','Equator','Espresso','Estuary','Evening','Eucalyptus','Excalibur','Exotic','Expanse','Exposure','Eyelet','Euphoria','Empire','Energy','Echo'],
        'F': ['Fern','Fernwood','Ficus','Firebrick','Flame','Fawnstone','Flint','Floral','Fluorescent','Foam','Fog','Forest','Fossil','Fox','Framboise','Freesia','Frost','Frozen','Fuchsia','Feldspar','Fulvous','Furnace','Fusion','Fjord','Feather','Fable','Falcon','Fawn','Fennel','Festival'],
        'G': ['Gainsboro','Gamboge','Garnet','Ginger','Glacier','Glitter','Gold','Goldenrod','Granite','Grape','Graphite','Grass','Gray','Green','Guava','Gunmetal','Galaxy','Gauntlet','Gauze','Gemstone','Genie','Geode','Glade','Glow','Gossamer','Grove','Growth','Guardian','Gumdrop','Gypsum'],
        'H': ['Harbor','Harvest','Hazel','Heather','Heliotrope','Henna','Hibiscus','Honey','Honeydew','Horizon','Hotmagenta','Hyacinth','Hydrangea','Hyperion','Hickory','Himalaya','Halo','Haze','Heron','Highland','Holly','Horizon','Hydra','Huckleberry','Hue','Hurricane','Hydra','Hummingbird','Hush','Hydric'],
        'I': ['Ice','Iceberg','Icicle','Illusion','Imperial','Indigo','Ink','Inkwell','Iris','Iron','Isle','Ivory','Idyll','Imperia','Impulse','Incense','Indus','Infinity','Inkstone','Interlude','Iolite','Isotope','Italics','Ivana','Ivy','Icon','Incisor','Infrared','Indra','Island'],
        'J': ['Jade','Jasper','Java','Jet','Jonquil','Jungle','Juniper','Jacaranda','Jam','Jasmine','Jeans','Jewel','Jockey','Jovial','Joy','Jubilee','Judge','Julep','Juno','Jigsaw','Jitterbug','Jingle','Junction','Jura','Jurassic','Justice','Juvenile','Journey','Jump','Jazz'],
        'K': ['Khaki','Kelp','Kelly','Kenya','Ketchup','Keylime','Kidney','Kimono','Kingfisher','Kite','Kiwi','Knockout','Kobe','Kodiak','Komodo','Kosmos','Krypton','Kumquat','Kiteblue','Kiss','Kelpwood','Kestrel','Kindle','Koi','Krill','Kitewing','Kernel','Kale','Keystone','Keepsake'],
        'L': ['Lagoon','Lake','Lamb','Lapis','Latte','Laurel','Lavender','Lead','Leaf','Lemon','Licorice','Lilac','Lime','Linen','Lion','Lipstick','Lobster','Logan','Loquat','Lotus','Lupine','Luster','Lynx','Lychee','Lyric','Labdanum','Lark','Lattice','Legacy','Lichen'],
        'M': ['Macaroon','Magenta','Mahogany','Maize','Malachite','Mandarin','Mango','Marigold','Maroon','Mauve','Meadow','Melon','Merlot','Metallic','Midnight','Mimosa','Mint','Misty','Mocha','Moss','Mulberry','Mushroom','Mustard','Myrrh','Mystic','Mystery','Magma','Meteor','Moonstone','Morning'],
        'N': ['Navy','Nebula','Nectar','Nickel','Night','Nile','Noble','Nopal','Nori','Nouvelle','Nutmeg','Nyx','Narcissus','Naples','Nasturtium','Natural','Neptune','Nectarine','Neutral','Nimbus','Ninja','Nopaline','North','Nougat','Nova','Novella','Nucleus','Nutria','Noriwood','Nyssa'],
        'O': ['Oasis','Obsidian','Ochre','Ocean','Octane','Odyssey','Oil','Okra','Olive','Onion','Onyx','Opal','Orange','Orbit','Orchid','Oregano','Origin','Oro','Otter','Outback','Owl','Oxide','Oxygen','Oyster','Ozark','Ozone','Oblique','Obscure','Offshoot','Oracle'],
        'P': ['Papaya','Paprika','Peach','Pear','Pearl','Peony','Pepper','Peridot','Periwinkle','Petal','Petrol','Pewter','Pine','Pink','Pistachio','Plum','Pomelo','Poppy','Porcelain','Powder','Praline','Primrose','Prune','Pumpkin','Purple','Putty','Pyrite','Pineapple','Poinsettia','Poseidon'],
        'Q': ['Quartz','Queen','Quince','Quill','Quench','Quokka','Quasar','Quaver','Quest','Quick','Quilt','Quirk','Quiver','Quokka','Quota','Quote','Quintet','Quorum','Quasarite','Quillwork','Quarry','Quetzal','Quintal','Quinoa','Quixotic','Quiz','Quiverleaf','Quiescent','Quillia','Quipo'],
        'R': ['Radish','Rain','Raisin','Raspberry','Raven','Red','Redwood','Rhubarb','Rose','Rosewood','Rouge','Ruby','Russet','Rust','Rye','Royal','Razzmatazz','Ramble','Ranch','Raphael','Rapier','Rapture','Rare','Razzle','Reed','Regal','Remedy','Resin','Rhino','River'],
        'S': ['Saffron','Sage','Salmon','Sand','Sapphire','Scarlet','Seafoam','Sepia','Shadow','Shell','Shimmer','Silver','Sky','Slate','Smoke','Snow','Sorbet','Spearmint','Spice','Spring','Steel','Stone','Strawberry','Sugar','Sunset','Sunflower','Surf','Sycamore','Symphony','Syrup'],
        'T': ['Taffy','Tan','Tangerine','Taupe','Teal','Terra','Thistle','Tiger','Tile','Timber','Toast','Topaz','Tourmaline','Truffle','Tulip','Turmeric','Turquoise','Twilight','Tyrian','Tabby','Tango','Tapestry','Tarot','Tatami','Tempest','Temple','Tennis','Thorn','Tide','Titan'],
        'U': ['Ultramarine','Umber','Ube','Uranium','Urban','Umbria','Utah','Utopia','Ulex','Ulva','Ural','Udon','Ulster','Ukon','Upland','Usher','Upland','Utility','Ulna','Uralic','Urbane','Upbeat','Upshot','Usnea','Uros','Ursa','Urtica','Utile','Ultrawave','Umbral'],
        'V': ['Vanilla','Vegas','Velvet','Venetian','Verdant','Verdigris','Vermilion','Verona','Veronica','Versailles','Vesper','Vibrant','Vienna','Vinyl','Viola','Violet','Viridian','Virtue','Vision','Vista','Vital','Volcano','Volt','Vulpine','Voyage','Vulcan','Vulture','Vespera','Vellum','Vireo'],
        'W': ['Walnut','Wasabi','Watermelon','Wheat','Whisper','White','Wildflower','Willow','Wine','Winter','Wisteria','Wood','Wool','Wrangler','Wren','Wrought','Wry','Wagon','Wake','Wallaby','Wave','Weather','Web','Wedding','Well','West','Whale','Whirl','Wing','Wish'],
        'X': ['Xanadu','Xanthic','Xebec','Xenon','Xerox','Xyline','Xi','Xmas','Xocolatl','Xray','Xtreme','Xyst','Xenia','Xango','Xeron','Xystus','Xiphoid','Xeric','Xenial','Xenolith','Xenopus','Xenotime','Xyloid','Xylograph','Xylose','Xylophone','Xystarch','Xystos','Xystum','Xylia'],
        'Y': ['Yacht','Yam','Yang','Yarrow','Yellow','Yeast','Yen','Yew','Yield','Yogi','Yolk','Young','Youth','Yucca','Yule','Yummy','Yarn','Yearn','Yeti','Yonder','Yabby','Yak','Yaffle','Yabbyfish','Yampee','Yapon','Yardstick','Yarke','Yarm','Yasmin'],
        'Z': ['Zaffre','Zebra','Zest','Zephyr','Zinc','Zinnia','Zircon','Zodiac','Zaffron','Zucchini','Zyra','Zither','Zirconia','Zendo','Zigzag','Zillion','Zircalloy','Zirkel','Zowie','Zanzibar','Zander','Zanier','Zagros','Zebrawood','Zelig','Zenith','Zerda','Zirkelite','Zymurgy','Zonda'],
    }
    return pools.get(letter, pools['A'])

    #this is a color pool to pull case names from, you can replace with any other words or other case name scheme you use
