ALTER TABLE custodians
  ADD COLUMN IF NOT EXISTS holds_gdrive BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS holds_gdrive_pending BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS holds_gdrive_failed BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS holds_gdrive_released BOOLEAN NOT NULL DEFAULT FALSE;
